# Generated by Django 6.1.1 on 2026-09-05 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100, unique=True)),
                ('stock', models.PositiveBigIntegerField()),
                ('quantity', models.CharField(choices=[('1KG', '1kg'), ('500G', '500g'), ('250G', '250g'), ('COUNT', 'count')], default='250G')),
                ('count', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_module.grocery')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
