# Generated by Django 6.1.1 on 2026-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='local_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
